version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GitRuntimeAssetsAZUSERSTAGEProject
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser/SIQA_GitRuntimeAssetsAZUSERSTAGEProject
  gitUsername: siqagituser
  gitBranch: main
